version: '3.8'

services:
  db:
    image: postgres:13
    container_name: ouroverde-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abrjam086
      POSTGRES_DB: ouro_verde
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: ouroverde-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ouro_verde
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=SUA_SENHA_AQUI
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  postgres_data: