
spring.datasource.url=jdbc:postgresql://localhost:5432/ouro_verde
spring.datasource.username=postgres
spring.datasource.password=abrjam086


spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true