spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ouro_verde
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password=1234
=======
spring.datasource.password=abrjam086
spring.datasource.driver-class-name=org.postgresql.Driver
>>>>>>> 583538fbfa249119eb3011bd05097ec1aa60c9d4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true